name: Bogdan's Ramblings
description: Technology blog
meta_description: "Bogdan's Ramblings; Technology blog"

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

logo: false
paginate: 15
baseurl: /
domain_name: 'http://bogdan.nimblex.net'
google_analytics: 'UA-1836794-3'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://bogdan.nimblex.net'
author:         'Bogdan Rădulescu'
