name: Bogdan's Ramblings
description: Technology blog
meta_description: "Bogdan's Ramblings; Technology blog"

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://bogdan.nimblex.net'
google_analytics: 'UA-1836794-3'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://bogdan.nimblex.net'
author:         'Bogdan Rădulescu'
